accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from accounts.views import sign_up

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", sign_up, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("home")),
    ),
    path("receipts/", include("receipts.urls")),
    path("accounts/", include("accounts.urls")),
]

receipts/urls.py
from django.urls import path

from receipts.views import (
    ReceiptListView,
    ReceiptCreateView,
    ExpenseCategoryListView,
    AccountListView,
    ExpenseCategoryCreateView,
    AccountCreateView,
)


urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", ReceiptCreateView.as_view(), name="create_receipt"),
    path(
        "categories/",
        ExpenseCategoryListView.as_view(),
        name="list_categories",
    ),
    path("accounts/", AccountListView.as_view(), name="accounts_list"),
    path(
        "categories/create/",
        ExpenseCategoryCreateView.as_view(),
        name="create_category",
    ),
    path(
        "accounts/create/", AccountCreateView.as_view(), name="create_account"
    ),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="categories",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="accounts",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(
        USER_MODEL,
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        ExpenseCategory,
        related_name="receipts",
        on_delete=models.CASCADE,
    )
    account = models.ForeignKey(
        Account,
        related_name="receipts",
        on_delete=models.CASCADE,
        null=True,
    )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login

# Create your views here.


def sign_up(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    form = UserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

receipts/views.py
from django.shortcuts import redirect
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView


from receipts.models import ExpenseCategory, Account, Receipt

# Create your views here.


class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/new.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        form.save_m2m()
        return redirect("home")

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model: ExpenseCategory
    template_name = "expense_category/list.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class AccountListView(LoginRequiredMixin, ListView):
    model: Account
    template_name = "account/list.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "expense_category/new.html"
    fields = ["name"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        form.save_m2m()
        return redirect("list_categories")

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "account/new.html"
    fields = ["name", "number"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        form.save_m2m()
        return redirect("accounts_list")

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)

receipts/templates/base.html
<!doctype html>
<html>
    <head>
        {% block title %}
        {% endblock title %}
    </head>
    <body>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'logout' %}">Logout</a>
                    </li>
                    <li>
                        <a href="{% url 'home' %}">Receipt List</a>
                    </li>
                    <li>
                        <a href="{% url 'create_receipt' %}">Create Receipt</a>
                    </li>
                    <li>
                        <a href="{% url 'list_categories' %}">Category List</a>
                    </li>
                    <li>
                        <a href="{% url 'create_category' %}">Create Category</a>
                    </li>
                    <li>
                        <a href="{% url 'accounts_list' %}">Accounts List</a>
                    </li>
                    <li>
                        <a href="{% url 'create_account' %}">Create Account</a>
                    </li>
                {% else %}
                    <li>
                        <a href="{% url 'signup' %}">Signup</a>
                    </li>
                    <li>
                        <a href="{% url 'login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
        {% block content %}
        {% endblock content %}
    </body>
</html>

receipts/templates/expense_category/list.html
{% extends "base.html" %}

{% block title %}
    <title>Expense Category</title>
{% endblock title %}
{% block content %}
    <main>
        <h1>Expense Category</h1>
        <p>
            <a href="{% url 'create_category' %}">Create a new category</a>
        </p>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Number of receipts</th>
                </tr>
            </thead>
            <tbody>
                {% for genre in expensecategory_list %}
                    <tr>
                        <td>{{ genre.name }}</td>
                        <td>{{ genre.receipts.all|length }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endblock content %}

receipts/templates/expense_category/new.html
{% extends "base.html" %}

{% block title %}
    <title>Create Category</title>
{% endblock title %}
{% block content %}
    <main>
        <div>
            <h1>Create Category</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Create</button>
            </form>
        </div>
    </main>
{% endblock content %}

receipts/templates/receipts/list.html
{% extends "base.html" %}

{% block title %}
    <title>Receipt List</title>
{% endblock title %}
{% block content %}
    <main>
        <h1>My Receipts</h1>
        <table>
            <thead>
                <tr>
                    <th>Vendor</th>
                    <th>Total</th>
                    <th>Tax</th>
                    <th>Date</th>
                    <th>Category</th>
                    <th>Account</th>
                </tr>
            </thead>
            <tbody>
                {% for biz in receipt_list %}
                    <tr>
                        <td>{{ biz.vendor }}</td>
                        <td>{{ biz.total }}</td>
                        <td>{{ biz.tax }}</td>
                        <td>{{ biz.date|date:"m-d-Y" }}</td>
                        <td>{{ biz.category }}</td>
                        <td>{{ biz.account }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endblock content %}

receipts/templates/receipts/new.html
{% extends "base.html" %}

{% block title %}
    <title>Create Receipt</title>
{% endblock title %}
{% block content %}
    <main>
        <div>
            <h1>Create Receipt</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                {% comment %} <p>
                <label for="username">Username:</label>
                <input type="text" name="username">
            </p>
            <p>
                <label for="password1">Password1:</label>
                <input type="password" name="password1">
            </p>
            <p>
                <label for="password2">Password2:</label>
                <input type="password" name="password2">
                </p> {% endcomment %}
                <button>Create</button>
            </form>
        </div>
    </main>
{% endblock content %}